
package org.niis.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "testServicePortType", targetNamespace = "http://test.x-road.fi/producer")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestServicePortType {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "data", targetNamespace = "http://test.x-road.fi/producer")
    @RequestWrapper(localName = "getRandom", targetNamespace = "http://test.x-road.fi/producer", className = "org.niis.ws.GetRandom")
    @ResponseWrapper(localName = "getRandomResponse", targetNamespace = "http://test.x-road.fi/producer", className = "org.niis.ws.GetRandomResponse")
    public String getRandom();

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "http://test.x-road.fi/producer")
    @RequestWrapper(localName = "helloService", targetNamespace = "http://test.x-road.fi/producer", className = "org.niis.ws.HelloService")
    @ResponseWrapper(localName = "helloServiceResponse", targetNamespace = "http://test.x-road.fi/producer", className = "org.niis.ws.HelloServiceResponse")
    public String helloService(
        @WebParam(name = "name", targetNamespace = "http://test.x-road.fi/producer")
        String name);

}
